# Generated by Django 6.0.2 on 2026-02-11 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_products', to='products.category')),
            ],
            options={
                'db_table': 'catalog_products',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.catalogproduct')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vendors.vendor')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories_slug_b4303a_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_60e7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['category'], name='catalog_pro_categor_6162df_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['vendor'], name='offers_vendor__f64686_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['catalog_product'], name='offers_catalog_5c0de2_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active'], name='offers_is_acti_5de943_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('vendor', 'catalog_product'), name='uniq_vendor_catalog_offer'),
        ),
    ]
