# Generated by Django 6.0.2 on 2026-02-18 05:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_delivery_area_order_delivery_building_and_more'),
        ('vendors', '0004_alter_vendor_commission_rate_alter_vendor_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('resolution_type', models.CharField(blank=True, choices=[('refund', 'Refund'), ('replace', 'Replacement'), ('partial_refund', 'Partial Refund'), ('cancel', 'Cancel Order'), ('other', 'Other')], default='', max_length=30)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='vendors.vendor')),
            ],
            options={
                'db_table': 'disputes',
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute_messages',
            },
        ),
    ]
