# Generated by Django 6.0.2 on 2026-02-17 23:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_area_order_delivery_building_and_more'),
        ('vendors', '0002_vendor_status_vendor_vendors_status_079e23_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.FloatField()),
                ('commission_amount', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendor_payouts',
            },
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_user_id_5e6fe3_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_store_n_6278dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_is_acti_04b085_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_status_079e23_idx',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commission_rate',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payouts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='vendorpayout',
            index=models.Index(fields=['vendor'], name='vendor_payo_vendor__ae1d99_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayout',
            index=models.Index(fields=['order'], name='vendor_payo_order_i_a10d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayout',
            index=models.Index(fields=['status'], name='vendor_payo_status_b7b211_idx'),
        ),
    ]
