# Generated by Django 6.0.2 on 2026-02-23 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0004_alter_vendor_commission_rate_alter_vendor_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/products/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_product_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='description_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='key_specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='short_description_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='stockist',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='tax_class',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='warranty_period',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='warranty_status',
            field=models.CharField(choices=[('none', 'No warranty'), ('manufacturer', 'Manufacturer warranty'), ('store', 'Store warranty')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='manage_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='special_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['in_stock'], name='offers_in_stoc_5379b2_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['price'], name='offers_price_7d10aa_idx'),
        ),
        migrations.AddField(
            model_name='catalogproductimage',
            name='catalog_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.catalogproduct'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='collections_slug_f91862_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_active'], name='collections_is_acti_b65401_idx'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='catalog_products', to='products.collection'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['is_active'], name='catalog_pro_is_acti_cc2bba_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['status'], name='catalog_pro_status_21da5c_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_bf7f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['name'], name='catalog_pro_name_890acd_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproductimage',
            index=models.Index(fields=['catalog_product'], name='catalog_pro_catalog_ea147a_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproductimage',
            index=models.Index(fields=['is_primary'], name='catalog_pro_is_prim_03932c_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproductimage',
            index=models.Index(fields=['sort_order'], name='catalog_pro_sort_or_52712c_idx'),
        ),
    ]
