# Generated by Django 6.0.2 on 2026-02-12 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_delivery_area_order_delivery_building_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=100)),
                ('mpesa_receipt', models.CharField(blank=True, default='', max_length=100)),
                ('result_code', models.CharField(blank=True, default='', max_length=20)),
                ('result_desc', models.CharField(blank=True, default='', max_length=255)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['order'], name='payments_order_i_b32b33_idx'), models.Index(fields=['user'], name='payments_user_id_7f3925_idx'), models.Index(fields=['provider'], name='payments_provide_b98dc8_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['checkout_request_id'], name='payments_checkou_48dc51_idx')],
            },
        ),
    ]
