# Generated by Django 6.0.2 on 2026-02-18 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0003_vendorpayout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commission_settings',
                'indexes': [models.Index(fields=['is_active'], name='commission__is_acti_965217_idx'), models.Index(fields=['created_at'], name='commission__created_aff99b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('global_update', 'Global Update'), ('vendor_override', 'Vendor Override')], db_index=True, max_length=30)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
            ],
            options={
                'db_table': 'commission_logs',
                'indexes': [models.Index(fields=['action'], name='commission__action_d8de81_idx'), models.Index(fields=['created_at'], name='commission__created_3177e0_idx')],
            },
        ),
    ]
