# Generated by Django 6.0.2 on 2026-02-18 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('vendors', '0004_alter_vendor_commission_rate_alter_vendor_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionlog',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_logs', to='vendors.vendor'),
        ),
    ]
